/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common/column_value.proto */

#ifndef PROTOBUF_C_common_2fcolumn_5fvalue_2eproto__INCLUDED
#define PROTOBUF_C_common_2fcolumn_5fvalue_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ColumnValue ColumnValue;


/* --- enums --- */


/* --- messages --- */

struct  ColumnValue
{
  ProtobufCMessage base;
  char *title;
  protobuf_c_boolean has_column_type_code;
  int32_t column_type_code;
  protobuf_c_boolean has_value;
  int32_t value;
  protobuf_c_boolean has_next_column;
  protobuf_c_boolean next_column;
};
#define COLUMN_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&column_value__descriptor) \
    , NULL, 0, 0, 0, 0, 0, 0 }


/* ColumnValue methods */
void   column_value__init
                     (ColumnValue         *message);
size_t column_value__get_packed_size
                     (const ColumnValue   *message);
size_t column_value__pack
                     (const ColumnValue   *message,
                      uint8_t             *out);
size_t column_value__pack_to_buffer
                     (const ColumnValue   *message,
                      ProtobufCBuffer     *buffer);
ColumnValue *
       column_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   column_value__free_unpacked
                     (ColumnValue *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ColumnValue_Closure)
                 (const ColumnValue *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor column_value__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_common_2fcolumn_5fvalue_2eproto__INCLUDED */
