/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common/column_value.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common/column_value.pb-c.h"
void   column_value__init
                     (ColumnValue         *message)
{
  static const ColumnValue init_value = COLUMN_VALUE__INIT;
  *message = init_value;
}
size_t column_value__get_packed_size
                     (const ColumnValue *message)
{
  assert(message->base.descriptor == &column_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t column_value__pack
                     (const ColumnValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &column_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t column_value__pack_to_buffer
                     (const ColumnValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &column_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ColumnValue *
       column_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ColumnValue *)
     protobuf_c_message_unpack (&column_value__descriptor,
                                allocator, len, data);
}
void   column_value__free_unpacked
                     (ColumnValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &column_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor column_value__field_descriptors[4] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ColumnValue, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column_type_code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ColumnValue, has_column_type_code),
    offsetof(ColumnValue, column_type_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ColumnValue, has_value),
    offsetof(ColumnValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_column",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ColumnValue, has_next_column),
    offsetof(ColumnValue, next_column),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned column_value__field_indices_by_name[] = {
  1,   /* field[1] = column_type_code */
  3,   /* field[3] = next_column */
  0,   /* field[0] = title */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange column_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor column_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ColumnValue",
  "ColumnValue",
  "ColumnValue",
  "",
  sizeof(ColumnValue),
  4,
  column_value__field_descriptors,
  column_value__field_indices_by_name,
  1,  column_value__number_ranges,
  (ProtobufCMessageInit) column_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
