#ifndef SPO_LAB_1_5_NET_H
#define SPO_LAB_1_5_NET_H

#define COMMAND_CODE_SELECT 0
#define COMMAND_CODE_CREATE 1
#define COMMAND_CODE_DROP 2
#define COMMAND_CODE_DELETE 3
#define COMMAND_CODE_INSERT 4

#endif //SPO_LAB_1_5_NET_H
